import { ColorTheme } from './types';

export const COLOR_THEMES: ColorTheme[] = [
  {
    name: '🔵 블루-그레이',
    description: '차분하고 전문적인 느낌',
    colors: {
      primary: '#1a73e8',
      primaryDark: '#004d99',
      secondary: '#5f6368',
      background: '#f8f9fa',
      text: '#3c4043',
      highlightBg: '#e8f0fe',
      infoBoxBg: '#e8f4fd',
      infoBoxBorder: '#1a73e8',
      warningBoxBg: '#fce8e6',
      warningBoxBorder: '#d93025',
      tableHeaderBg: '#e8eaed',
      tableBorder: '#dadce0',
      tableEvenRowBg: '#f1f3f4',
    },
  },
  {
    name: '🌿 그린-오렌지',
    description: '활기차고 친근한 느낌',
    colors: {
      primary: '#34a853',
      primaryDark: '#1e8e3e',
      secondary: '#ea8600',
      background: '#f1f8e9',
      text: '#333333',
      highlightBg: '#fef6e0',
      infoBoxBg: '#e6f4ea',
      infoBoxBorder: '#34a853',
      warningBoxBg: '#fde293',
      warningBoxBorder: '#f9ab00',
      tableHeaderBg: '#e6f4ea',
      tableBorder: '#a5d6a7',
      tableEvenRowBg: '#f1f8e9',
    },
  },
  {
    name: '💜 퍼플-옐로우',
    description: '세련되고 창의적인 느낌',
    colors: {
      primary: '#8e44ad',
      primaryDark: '#6200ea',
      secondary: '#f1c40f',
      background: '#fdf6e3',
      text: '#2c3e50',
      highlightBg: '#fcf8e3',
      infoBoxBg: '#f3e5f5',
      infoBoxBorder: '#8e44ad',
      warningBoxBg: '#fff9c4',
      warningBoxBorder: '#f1c40f',
      tableHeaderBg: '#f3e5f5',
      tableBorder: '#ce93d8',
      tableEvenRowBg: '#faf3fb',
    },
  },
  {
    name: '🍵 틸-라이트그레이',
    description: '안정적이고 현대적인 느낌',
    colors: {
      primary: '#00796b',
      primaryDark: '#004d40',
      secondary: '#607d8b',
      background: '#eceff1',
      text: '#263238',
      highlightBg: '#e0f2f1',
      infoBoxBg: '#e0f7fa',
      infoBoxBorder: '#00796b',
      warningBoxBg: '#ffebee',
      warningBoxBorder: '#c62828',
      tableHeaderBg: '#cfd8dc',
      tableBorder: '#b0bec5',
      tableEvenRowBg: '#eceff1',
    },
  },
  {
    name: '🧱 테라코타-라이트그레이',
    description: '따뜻하고 편안한 느낌',
    colors: {
      primary: '#e57373',
      primaryDark: '#c62828',
      secondary: '#757575',
      background: '#fafafa',
      text: '#424242',
      highlightBg: '#ffcdd2',
      infoBoxBg: '#fbe9e7',
      infoBoxBorder: '#ff8a65',
      warningBoxBg: '#fff3e0',
      warningBoxBorder: '#ffa726',
      tableHeaderBg: '#eeeeee',
      tableBorder: '#e0e0e0',
      tableEvenRowBg: '#f5f5f5',
    },
  },
   {
    name: '👔 클래식 블루',
    description: '신뢰할 수 있고 안정적인 느낌',
    colors: {
      primary: '#0f4c81',
      primaryDark: '#002f6c',
      secondary: '#77aaff',
      background: '#f0f4f8',
      text: '#333333',
      highlightBg: '#e3f2fd',
      infoBoxBg: '#e3f2fd',
      infoBoxBorder: '#0f4c81',
      warningBoxBg: '#ffebee',
      warningBoxBorder: '#d32f2f',
      tableHeaderBg: '#d6e4f0',
      tableBorder: '#b0bec5',
      tableEvenRowBg: '#f0f4f8',
    },
  },
  {
    name: '🌳 네이처 그린',
    description: '생기 있고 조화로운 느낌',
    colors: {
      primary: '#2e7d32',
      primaryDark: '#005005',
      secondary: '#aed581',
      background: '#f1f8e9',
      text: '#212121',
      highlightBg: '#dcedc8',
      infoBoxBg: '#e8f5e9',
      infoBoxBorder: '#2e7d32',
      warningBoxBg: '#fffde7',
      warningBoxBorder: '#fbc02d',
      tableHeaderBg: '#c8e6c9',
      tableBorder: '#a5d6a7',
      tableEvenRowBg: '#f1f8e9',
    },
  },
];

export const EEAT_CATEGORIES_DATA: { [key: string]: string[] } = {
    "심층 가이드 및 'How-to'": ["IT/기술", "건강/피트니스", "금융/투자", "요리/레시피", "DIY/공예", "학습/교육", "운세/명리학"],
    "비교 및 분석": ["전자기기", "소프트웨어/앱", "금융 상품", "자동차", "여행지/숙소", "온라인 강의"],
    "최신 정보 및 트렌드": ["기술 동향", "사회/문화", "경제 뉴스", "패션/뷰티", "엔터테인먼트", "스포츠", "운세/명리학"],
    "사례 연구 및 성공 사례": ["비즈니스/마케팅", "자기계발", "재테크 성공기", "건강 개선", "학습법", "커리어 전환"],
    "개인 경험 (후기, 경험담)": ["제품 사용 후기", "여행기", "맛집 탐방", "도서/영화 리뷰", "육아 일기", "취미 생활", "운세/명리학"]
};

export const EVERGREEN_SUBCATEGORIES: string[] = [
    "IT/기술",
    "경제/재테크",
    "건강/자기계발",
    "생활/라이프스타일",
    "교육/학습",
    "취업/커리어",
    "여행",
    "취미",
    "운세/명리학"
];